export const DEMO = {
  titulo: "Lição 13 - Luz do Mundo (20 a 26 de Junho)",
  semana: "2026-W25",
  trimestre: "Teste",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-06-20",
      titulo: "TEASER",
      conteudo: "O último capítulo do livro Os Embaixadores faz um chamado inspirador para darmos continuidade ao legado dos heróis espirituais. Ellen White escreveu: 'O inimigo fez de tudo para deter a obra confiada aos construtores do Senhor. Todavia, Deus levantou obreiros que defenderam a fé com clareza e poder. Como os apóstolos, muitos morreram cumprindo seu dever. Contudo, a edificação do templo prosseguiu firmemente... trouxeram, ao fundamento, material que será preservado pela eternidade' (Página 273).\n\nAgora é o tempo de tomar a decisão de dedicar-se completamente ao Senhor e ao Seu serviço. Todos são chamados para ser testemunhas. Deus deseja que todos sejamos ativos no evangelismo – não importa nossos traços de personalidade. Pela graça divina, podemos nos tornar embaixadores de Cristo.",
      versiculoChave: { texto: "Juntos, somos sua casa, edificados sobre os alicerces dos apóstolos...", referencia: "Efésios 2:19-22" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo o texto, o que o inimigo fez em relação à obra?", opcoes: ["Ignorou os construtores", "Fez de tudo para deter a obra", "Ajudou na edificação do templo", "Desanimou apenas os apóstolos"], correta: 1, explicacao: "O inimigo fez de tudo para deter a obra confiada aos construtores do Senhor." },
        { id: "d1q2", pergunta: "O texto nos chama, pela graça divina, a nos tornarmos o quê?", opcoes: ["Apenas ouvintes", "Embaixadores de Cristo", "Construtores de templos físicos", "Juízes do mundo"], correta: 1, explicacao: "Pela graça divina, podemos nos tornar embaixadores de Cristo." },
        { id: "d1q3", pergunta: "O que continuou a acontecer contudo, segundo Ellen White?", opcoes: ["A edificação do templo prosseguiu firmemente", "A igreja desistiu de sua missão", "Os apóstolos fugiram todos", "A fé foi esquecida por séculos"], correta: 0, explicacao: "A edificação do templo prosseguiu firmemente." },
        { id: "d1q4", pergunta: "Deus deseja que todos sejamos ativos no:", opcoes: ["Isolamento monástico", "Julgamento alheio", "Evangelismo", "Estudo secular profundo"], correta: 2, explicacao: "Deus deseja que todos sejamos ativos no evangelismo." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-06-21",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Os textos bíblicos para o estudo desta semana se concentram em Mateus 16:18, Efésios 2:19-22 e Apocalipse 7:9-17. Leia em sua Bíblia sobre o chamado de Pedro, a explicação de Paulo sobre quem é realmente a pedra angular e a visão que João teve de uma grande multidão vestida de branco diante do trono e do Cordeiro.\n\nQue palavras ou frases lhe dão um senso de esperança? Qual é a ideia principal em cada texto? Qual é o tema presente nos três textos? Como você pode ser luz em um mundo escuro durante esta semana?",
      versiculoChave: { texto: "A explicação de Paulo sobre quem é realmente a pedra angular...", referencia: "Efésios 2:19-22" },
      perguntas: [
        { id: "d2q1", pergunta: "O estudo desta semana se concentra em quais textos bíblicos?", opcoes: ["Gênesis, Êxodo e Levítico", "Mateus 16, Efésios 2 e Apocalipse 7", "Marcos 10, Atos 2 e Romanos 8", "João 3, 1 Coríntios 13 e Hebreus 11"], correta: 1, explicacao: "Estaremos estudando Mateus 16:18, Efésios 2:19-22 e Apocalipse 7:9-17." },
        { id: "d2q2", pergunta: "A explicação do Apóstolo Paulo nesses capítulos é sobre?", opcoes: ["Viagens missionárias", "Como construir tendas", "Quem é realmente a pedra angular e como a Igreja é edificada", "Como enfrentar reis em tribunais"], correta: 2, explicacao: "Ele orienta sobre quem é realmente a pedra angular na construção da Igreja." },
        { id: "d2q3", pergunta: "O que João viu em Apocalipse 7?", opcoes: ["Uma cidade destruída", "Uma grande multidão vestida de branco", "Um exército terrestre", "Muitas pedras preciosas caindo"], correta: 1, explicacao: "A visão de João foi de uma grande multidão vestida de branco em redenção." },
        { id: "d2q4", pergunta: "A ideia principal proposta como reflexão pessoal é:", opcoes: ["Como ser luz num mundo escuro nesta semana?", "Como arrecadar dinheiro?", "Como ler mais rápido?", "Como evitar os problemas da vida?"], correta: 0, explicacao: "Como você pode ser luz em um mundo escuro durante esta semana." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-06-22",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Efésios 2:19-22.\n\nDe acordo com um dicionário de definições, a pedra angular era a pedra fundamental utilizada nas antigas construções, caracterizada por ser a primeira a ser assentada na esquina do edifício, formando um ângulo reto entre duas paredes. A partir da pedra angular, eram definidas as colocações das outras pedras, alinhando toda a construção. O apóstolo Paulo esclarece que Jesus é a pedra angular, que torna o edifício bem ajustado e consolidado.\n\nAinda usando o exemplo de construções e pedras, Ellen White escreveu: 'Os apóstolos edificaram sobre a Rocha Eterna. Para esse fundamento, trouxeram as pedras que tiraram do mundo... Contudo, com fé e coragem, continuaram avançando' (Os Embaixadores, p. 273).\n\nTodos nós podemos ser 'pedras' úteis na edificação da igreja. Só precisamos permitir que o Construtor-Mestre nos coloque no lugar certo!",
      versiculoChave: { texto: "Jesus Cristo é a principal pedra de esquina...", referencia: "Efésios 2:20" },
      perguntas: [
        { id: "d3q1", pergunta: "Na antiguidade, o que era a 'pedra angular'?", opcoes: ["A pedra de tropeço", "A primeira pedra assentada que alinhava toda a construção", "A pedra usada para decoração", "O último tijolo do telhado"], correta: 1, explicacao: "Era a primeira pedra assentada na esquina, alinhando o restante do edifício." },
        { id: "d3q2", pergunta: "Quem o apóstolo Paulo diz ser a pedra angular?", opcoes: ["Pedro", "Senhores de Roma", "O próprio Paulo", "Jesus"], correta: 3, explicacao: "Paulo esclarece que Jesus é a pedra angular." },
        { id: "d3q3", pergunta: "Nós podemos ser o quê na edificação da igreja, segundo a mensagem?", opcoes: ["Estatísticas do reino", "'Pedras' úteis", "Tijolos de palha", "Árvores no jardim"], correta: 1, explicacao: "Todos nós podemos ser 'pedras' úteis na edificação da igreja." },
        { id: "d3q4", pergunta: "O que precisamos permitir que o Construtor-Mestre faça?", opcoes: ["Nos deixe de fora", "Nos coloque onde nós quisermos", "Nos coloque no lugar certo", "Nos deixe para sempre parados"], correta: 2, explicacao: "Permitir que o Construtor-Mestre nos coloque no lugar certo!" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-06-23",
      titulo: "MAKING OF",
      conteudo: "A igreja, no tempo dos apóstolos, defendia conceitos totalmente diferentes da cultura vigente. Na igreja cristã não havia divisão social, nem discriminação de mulheres. Em vez de serem rejeitados, os pobres e doentes eram acolhidos.\n\nUma interpretação equivocada a respeito das palavras de Jesus - 'Você é Pedro e sobre esta pedra edificarei a Minha igreja' - levou a Igreja Católica Romana a considerar o apóstolo o primeiro papa. A explicação a respeito de quem é a pedra angular esclarece esse assunto (Ef 2:19-22).\n\nNo ano 40 d.C., estimava-se que apenas 1 em cada 1.000 pessoas no Império Romano era seguidora de Jesus. Em 350 d.C., surpreendentemente 56% da população romana se declarava cristã. Um índice de crescimento de 40% por década!\n\nTanto Pedro como Paulo terminaram seu ministério em Roma. Paulo foi decapitado. Pedro, por sua vez, como judeu e estrangeiro, foi açoitado e crucificado de cabeça para baixo. Em Atos 2:47 lemos que a igreja cristã tinha 'a simpatia do povo'.",
      versiculoChave: { texto: "louvando a Deus e tendo a simpatia de todo o povo...", referencia: "Atos 2:47" },
      perguntas: [
        { id: "d4q1", pergunta: "Segundo o texto, qual interpretação equivocada foi feita sobre as palavras 'Você é Pedro...'?", opcoes: ["A Igreja não precisaria de líderes", "A Igreja Católica a usou para considerar o apóstolo o primeiro papa", "Que a pedra fundamental era o próprio livro de Gênesis", "Qualquer discípulo batizava mais que ele"], correta: 1, explicacao: "Levou-se a interpretar que Pedro era considerado o primeiro papa." },
        { id: "d4q2", pergunta: "Como a igreja no tempo dos apóstolos lidava com a estrutura da sociedade e cultura?", opcoes: ["Copiava os costumes escravagistas de Roma", "Rejeitava os pobres e doentes", "Não havia divisão social nem discriminação", "Segregava mulheres em cerimônias diárias"], correta: 2, explicacao: "A igreja primitiva não tinha divisão social, e acolhia as mulheres, doentes e pobres." },
        { id: "d4q3", pergunta: "Como o apóstolo Pedro morreu em Roma?", opcoes: ["Decapitado velozmente", "Apedrejado longe da praça de Roma", "Açoitado e crucificado de cabeça para baixo", "Morreu durante o sono velho e descansado"], correta: 2, explicacao: "Pedro foi açoitado e crucificado de cabeça para baixo porque não se considerava digno de morrer como Cristo." },
        { id: "d4q4", pergunta: "Em Atos 2:47 é dito que a igreja inicial cristã tinha...", opcoes: ["A repulsa popular", "Muito ouro e prédios", "A simpatia do povo", "Apenas pessoas ricas"], correta: 2, explicacao: "A Igreja desfrutava da simpatia de todo o povo." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-06-24",
      titulo: "EXTRAS",
      conteudo: "Nos primeiros séculos as pessoas compreenderam a visão de Cristo para a igreja. Espectadores ficaram maravilhados com a graça radical que os cristãos mostraram para com todas as pessoas – o enfermo, o pobre, o marginalizado. E esse grupo radical de crentes nem mesmo possuía um nome.\n\nEles eram simplesmente chamados ecclesia – o que não significa 'prédio' ou 'serviço de adoração' ou a 'torre da igreja'. Significa 'assembleia' porque igreja é isto – é uma reunião de pessoas comuns comprometidas a fazer brilhar a luz de Jesus aonde quer que forem.\n\nA igreja é uma força-tarefa com a missão de iluminar um mundo escuro. É o corpo de Cristo, do qual somos membros. Quando estamos servindo, amando, doando, encorajando, ajudando outros e fazendo brilhar a luz – então somos a igreja! Isso significa que somos os únicos evangelistas que Jesus tem para Sua igreja.",
      versiculoChave: { texto: "Vós sois a luz do mundo. Não se pode esconder a cidade edificada sobre um monte.", referencia: "Mateus 5:14" },
      perguntas: [
        { id: "d5q1", pergunta: "O que a palavra grega 'ecclesia' significa no contexto dos primeiros crentes?", opcoes: ["Prédio monumental luxuoso", "Serviço de música puramente acapela e sacra", "A torre mais alta e divina de todas", "Assembleia/reunião de pessoas comuns"], correta: 3, explicacao: "Significa assembleia, uma reunião de pessoas prontas a fazer o bem aonde estiverem." },
        { id: "d5q2", pergunta: "Para quem os crentes mostravam uma impressionante graça radical?", opcoes: ["Apenas para com autoridades do Império", "Somente a quem fosse da própria nacionalidade deles", "Para o enfermo, o pobre e o marginalizado em geral", "Somente famílias de sangue sem enfermidades contagiosas"], correta: 2, explicacao: "Mostravam amor para o enfermo, o pobre e o marginalizado de todos." },
        { id: "d5q3", pergunta: "Quando somos verdadeiramente a igreja de Cristo na terra?", opcoes: ["Enquanto estamos ouvindo palestras em locais silenciosos", "Apenas sentados apreciando boa cantoria de domingo", "Quando praticamos as boas obras com força política", "Quando amamos, ajudamos os outros e doamos com encorajamento"], correta: 3, explicacao: "Amando, doando, encorajando e ajudando outros." },
        { id: "d5q4", pergunta: "Quem são os 'únicos evangelistas' que Jesus tem para Sua igreja, pela lógica do texto?", opcoes: ["Os príncipes, governantes no mundo atual", "Nós - pessoas comprometidas com Sua graça no agir em união", "Sábios dedicados exclusivamente em cavernas no alto deserto", "Inteligências de luz angelicais nos enviando inspirações e livros"], correta: 1, explicacao: "Nós somos a única missão da força da igreja (missionários físicos) que Ele conta aqui e hoje." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-06-25",
      titulo: "PANORÂMICA",
      conteudo: "Leia o último capítulo (58) do livro Os Embaixadores, cujo título é 'Futuro Glorioso'. As palavras de Ellen White são emocionantes. Veja o que ela disse no primeiro parágrafo: 'Muitos séculos se passaram desde que os apóstolos descansaram de seus trabalhos, mas a história de seus sacrifícios por Cristo ainda está entre os tesouros mais preciosos da igreja. Quando esses mensageiros da cruz saíram para pregar o evangelho, Deus revelou Sua glória como ninguém jamais tinha visto antes. Eles levaram o evangelho a todas as nações em uma única geração' (Os Embaixadores, p. 272).\n\nQue sonho! Mesmo sendo tão poucos, os apóstolos levaram o evangelho a todas as nações em uma única geração. [...] '[Cristo] nos manda sair e falar as Suas palavras, sentindo Seu santo toque em nossos lábios. Não há nada que o Salvador deseje mais do que pessoas que representem Seu Espírito e caráter para o mundo... Se ela for fiel a Ele, obedecendo a todos os Seus mandamentos, nenhum poder será capaz de resistir a ela.' (Os Embaixadores, p. 274)",
      versiculoChave: { texto: "Ide por todo o mundo, pregai o evangelho a toda criatura.", referencia: "Marcos 16:15" },
      perguntas: [
        { id: "d6q1", pergunta: "Segundo citação de Os Embaixadores, o que os apóstolos conquistaram milagrosamente?", opcoes: ["Ficaram ricos e famosos no Império durante o resto dos dias", "Levaram o evangelho a todas as nações em uma única geração!", "Conquistaram todo o senado romano a favor de isenções aos pobres escravos cristãos convertidos sem custo nenhum do erário romano", "Venceram táticas de guerras espalhando as novidades dos cristãos pelas nações europeias."], correta: 1, explicacao: "Eles levaram o evangelho a todas as nações num curto período de tempo equivalente a uma única geração da humanidade viva na época da pregação evangélica." },
        { id: "d6q2", pergunta: "Qual o título do capítulo final citado no texto do devocional?", opcoes: ["Morte dos Apóstolos Escritos pelo Futuro Maior", "A Grande Tribulação Final Antes e Ainda Antes do Seu Fim", "O Fim dos Heróis Antigos da Profecia Final e Apocalipse do Começo Certo", "Futuro Glorioso"], correta: 3, explicacao: "Futuro Glorioso é o nome do capítulo." },
        { id: "d6q3", pergunta: "O que o Salvador mais deseja da igreja?", opcoes: ["Festivais grandiosos nas catedrais de ouro", "Que sejamos ricos", "Pessoas que representem o Seu Espírito e caráter", "Discussões teológicas em conselhos do Sinédrio"], correta: 2, explicacao: "Ele deseja pessoas que o representem perante o mundo, reproduzindo Seu caráter entre si e os demais do nosso redil ou não amando uns aos outros. Tudo isso é revelado ali." },
        { id: "d6q4", pergunta: "O que acontecerá se a igreja for fiel a Cristo e obediente?", opcoes: ["Fará paz com o mundo", "Nenhum poder será capaz de resistir a ela", "Terá fim em breve", "Se tornará irrelevante logo no primeiro obstáculo no Império da época e também até agora de nossa história na humanidade atual."], correta: 1, explicacao: "Nenhum poder fará nada contra essa força que transita e irradia o evangelho fiel de Sua promessa real ali nas Escrituras à nós todos no hoje das nossas vivências." }
      ]
    },
    {
      id: 7, diaSemana: "Sexta", data: "2026-06-26",
      titulo: "OFF",
      conteudo: "Depois de relembrarmos o significado de igreja e nos emocionarmos com a maneira maravilhosa como os apóstolos cumpriram sua missão, resta-nos perguntar: Como podemos ajudar? De que forma a estrutura desse grande templo pode ser completada?\n\nA resposta está na página 274, do livro Os Embaixadores. 'Nós, que estamos vivendo nesta época, devemos levar para o fundamento material que resista à prova de fogo – ouro, prata e pedras preciosas. [...] O cristão que apresenta a Palavra da vida fielmente está levando ao fundamento material que resistirá e, no reino, ele será honrado como um construtor sábio. [...] Se a igreja se revestir do manto da justiça de Cristo e abandonar toda aliança com o mundo, ela estará pronta para o amanhecer de um dia glorioso. A verdade, ao passar por aqueles que a rejeitam, vencerá. Quando a mensagem de Deus encontrar oposição, Ele dará força adicional. Cheia do poder divino, ela atravessará as barreiras mais fortes e vencerá todo obstáculo.'",
      versiculoChave: { texto: "Ora, se alguém edifica sobre o fundamento com ouro, prata, pedras preciosas, madeira, feno, palha...", referencia: "1 Coríntios 3:12" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo Os Embaixadores, o que deve ser levado como fundamento material para resistir à prova de fogo?", opcoes: ["Materiais perenes tais como: pedras não preciosas, apenas palha em abundância.", "Metais e pedras de todos os tipos para enfeite geral e feno bem amarrado nas laterais do muro de pedras que desabavam à noite fria e triste das horas do dia.", "Muitas das antigas filosofias", "Ouro, prata e pedras preciosas"], correta: 3, explicacao: "Esse 'ouro, prata e pedras preciosas' figuram como crentes maduros alcançando vida resistente que levamos no fundamento de nossos esforços!" },
        { id: "d7q2", pergunta: "O cristão que apresenta a Palavra fielmente será honrado como o quê?", opcoes: ["Sábio doutor nas cortes", "Senhor de província em locais importantes das cortes", "Mártir glorioso para sempre em todo local daquela era dos apóstolos, o primeiro papa na terra de nossa época antiga para a atualidade sem dúvida alguma no processo histórico.", "Construtor sábio"], correta: 3, explicacao: "Será honrado, por Cristo, como construtor sábio!" },
        { id: "d7q3", pergunta: "O que a igreja deve abandonar para estar pronta para um dia glorioso?", opcoes: ["Obras de caridade em áreas carentes do continente inteiro da civilização ocidental.", "Aliança com o mundo e qualquer conformismo de caráter secular nocivo", "Roupas sem sofisticação e falta de dinheiro do tesouro real que ajudou muito. Por que não aproveitar a riqueza temporal para si ali em nossos prazeres passageiros naquelas oportunidades abertas por ele sem perigo das consequências ali? ", "Suas características originais que marcaram sua criação por Jesus com os apóstolos naquele dia do princípio das grandes novidades sem volta."], correta: 1, explicacao: "Deve abandonar toda aliança com o mundo com coragem e persistir confiando nEle em seu todo e seu Espírito perante todos os obstáculos da humanidade, etc." },
        { id: "d7q4", pergunta: "O que acontecerá quando a mensagem de Deus encontrar oposição?", opcoes: ["Ele recuará em todos os sentidos de nossa experiência nos campos em que houver qualquer ameaça militar nas cidades inimigas.", "Não fará diferença nenhuma para ninguém dos seguidores mais fanáticos.", "Deus apenas dará castigo ao povo que Ele ama de volta com severidade de um juiz impiedoso, sem nenhuma dó das suas intenções reais sem compaixão àquele tempo com as pessoas da Terra", "Ele dará força adicional, atravessando as barreiras e obstáculos."], correta: 3, explicacao: "Deus dará força e vencerá os obstáculos e barreiras cheia do poder." }
      ]
    }
  ]
};

export const PROVADO_PELO_FOGO = {
  titulo: "Lição 1 - Entregando a Vida pela Fé (27 de junho a 3 de julho)",
  semana: "2026-W26",
  trimestre: "Provado pelo Fogo",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-06-27",
      titulo: "TEASER",
      conteudo: "Os primeiros cristãos enfrentaram situações terríveis para se manterem firmes na fé. Já é difícil imaginar ter que passar por situações assim, que dirá estar disposto a resisti-las. No entanto, os primeiros cristãos encontraram coragem para enfrentar o pior. O relacionamento que mantinham com Deus era tão forte que preferiram ser martirizados a abandonar suas crenças.\n\nUma crença superficial não é capaz de oferecer esse nível de coragem. Por causa de crenças profundamente enraizadas, pessoas se dispõem a guerrear e a matar outros seres humanos, mas nenhuma crença preenche o coração humano de coragem para aceitar a morte pacificamente. Apenas o poder de Deus pode fazer com que um pesadelo se torne um ato heroico.\n\nEm Mateus 24, os discípulos perguntaram a Jesus quais seriam os sinais do tempo do fim. Jesus lhes respondeu de uma maneira singular. Proferiu uma profecia dupla. Advertiu-os a respeito da destruição de Jerusalém que ocorreria em 70 d.C. e revelou-lhes também como seria o fim dos tempos. Jesus contou apenas aquilo que era importante para a época. Eles precisavam ser advertidos a respeito da destruição de Jerusalém para que aqueles que cressem pudessem fugir antes da catástrofe. Precisavam também saber quais seriam os sinais do fim para que pudessem passar as informações adiante. Se observassem os sinais, estariam a salvo, mesmo sem saber exatamente o que aconteceria. O mesmo se aplica a nós hoje.",
      versiculoChave: { texto: "O servo fiel e sensato é aquele a quem seu senhor encarrega de gerir os outros servos da casa e alimentá-los. Se o senhor voltar e constatar que o servo fez um bom trabalho, haverá recompensa.", referencia: "Mateus 24:45,46" },
      perguntas: [
        { id: "d1q1", pergunta: "Sobre o que os discípulos perguntaram a Jesus, em Mateus 24?", opcoes: ["Quando construiriam um novo templo", "Quais seriam os sinais do tempo do fim", "Quando Roma cairia", "Como vencer os fariseus"], correta: 1, explicacao: "Eles perguntaram sobre os sinais do tempo do fim." },
        { id: "d1q2", pergunta: "A profecia de Jesus em Mateus 24 foi:", opcoes: ["Simples e única", "Dupla — Jerusalém e o fim dos tempos", "Apenas sobre o templo", "Sem nenhuma explicação"], correta: 1, explicacao: "Proferiu uma profecia dupla sobre a destruição de Jerusalém e o fim dos tempos." },
        { id: "d1q3", pergunta: "Em que ano ocorreu a destruição de Jerusalém mencionada no texto?", opcoes: ["33 d.C.", "70 d.C.", "100 d.C.", "1844"], correta: 1, explicacao: "Ocorreu em 70 d.C." },
        { id: "d1q4", pergunta: "O texto-chave desta semana está em:", opcoes: ["Mateus 5", "Mateus 24:45,46", "Apocalipse 14", "Daniel 8"], correta: 1, explicacao: "O texto-chave está em Mateus 24:45,46." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-06-28",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Jesus deu aos discípulos um breve resumo do cristianismo e dos eventos que aconteceriam antes de Sua vinda. Leia em sua Bíblia os textos de Mateus 24:3-14,30-39. Havia uma boa razão para Jesus dar a informação dessa maneira, aos poucos. Ele queria que os discípulos estivessem preparados, mas não desejava que eles sofressem antecipadamente. Depois de ler a passagem bíblica, responda às perguntas a seguir:\n\n- A maneira como Jesus conversou com os discípulos demonstra como era o relacionamento que Ele mantinha com Seus companheiros. Como eles desenvolveram esse tipo de comunicação?\n- Quão importantes eram essas informações nos dias de Jesus? Quão importantes elas são para nós hoje?\n- Que coisas hoje são parecidas com as dos 'dias de Noé'?\n- Que sentimento essa descrição do fim dos tempos desperta em você?",
      versiculoChave: { texto: "Jesus deu aos discípulos um breve resumo do cristianismo e dos eventos que aconteceriam antes de Sua vinda...", referencia: "Mateus 24:3-14,30-39" },
      perguntas: [
        { id: "d2q1", pergunta: "Os textos lidos hoje estão em qual passagem?", opcoes: ["Mateus 24:3-14,30-39", "Lucas 21", "Apocalipse 11", "Romanos 1"], correta: 0, explicacao: "Estão em Mateus 24:3-14,30-39." },
        { id: "d2q2", pergunta: "Jesus comparou os últimos dias com os dias de:", opcoes: ["Davi", "Noé", "Moisés", "Daniel"], correta: 1, explicacao: "Ele comparou com os dias de Noé." },
        { id: "d2q3", pergunta: "Por que Jesus deu a informação 'aos poucos', segundo o roteiro?", opcoes: ["Para confundir os discípulos", "Para que estivessem preparados sem sofrer antecipadamente", "Porque não sabia o futuro", "Porque ninguém perguntou"], correta: 1, explicacao: "Ele não queria que eles sofressem antecipadamente." },
        { id: "d2q4", pergunta: "O objetivo central da reflexão de hoje é pensar sobre:", opcoes: ["A construção do templo", "O relacionamento de Jesus com os discípulos e os sinais do fim", "A lei de Moisés", "Os milagres de Jesus"], correta: 1, explicacao: "É pensar sobre o relacionamento com os discípulos e os eventos do fim." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-06-29",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em Mateus 24:45,46. Jesus contou seis ilustrações para mostrar aos discípulos a importância de vigiar e estar prontos. Essa foi a segunda delas.\n\nO Comentário Bíblico Adventista diz o seguinte a respeito desse texto: 'Esta parábola se aplica especialmente aos líderes religiosos e espirituais da família da fé, cujo dever é suprir as necessidades de seus membros e que, por preceito e exemplo, devem testemunhar de sua crença na proximidade da vinda de Cristo'.\n\nPense nas pessoas que têm servido de referência para você como líderes espirituais. Para facilitar, estas são algumas das características que você pode considerar: Elas 'respiram' o ar do Céu e vivem de acordo com o que professam crer. Quando falam das coisas de Deus, os olhos delas brilham. A maior expectativa da vida delas é a vinda de Jesus. São pessoas fiéis a Deus e que assumem com alegria a responsabilidade de ajudar os outros a serem fiéis também.\n\nQuando ouviram essa parábola, os discípulos não sabiam que esse seria exatamente o papel que eles deveriam desempenhar quando Jesus voltasse para o Céu. Mas, quando o tempo chegou, eles demonstraram ser fiéis e sensatos. Cumpriram com alegria a missão que o Senhor lhes confiou e 'alimentaram' os que vieram depois deles.",
      versiculoChave: { texto: "Mesmo quando eu andar por um vale de trevas e morte, não temerei perigo algum, pois Tu estás comigo; a Tua vara e o Teu cajado me protegem", referencia: "Salmo 23:4" },
      perguntas: [
        { id: "d3q1", pergunta: "A parábola do servo fiel e sensato se aplica especialmente a quem, segundo o Comentário Bíblico Adventista?", opcoes: ["Aos romanos", "Aos líderes religiosos e espirituais", "Aos fariseus", "Aos soldados"], correta: 1, explicacao: "Aplica-se aos líderes religiosos e espirituais." },
        { id: "d3q2", pergunta: "Qual característica de um bom líder espiritual é citada no texto de hoje?", opcoes: ["Riqueza material", "Eloquência", "Os olhos brilham ao falar das coisas de Deus", "Popularidade"], correta: 2, explicacao: "Os olhos brilham ao falar das coisas de Deus." },
        { id: "d3q3", pergunta: "O Salmo citado para completar os espaços em branco hoje é:", opcoes: ["Salmo 23", "Salmo 119", "Salmo 91", "Salmo 51"], correta: 0, explicacao: "É o Salmo 23." },
        { id: "d3q4", pergunta: "Qual é a maior expectativa da vida de um bom líder espiritual, segundo o texto?", opcoes: ["Reconhecimento público", "A vinda de Jesus", "Riqueza", "Poder"], correta: 1, explicacao: "A maior expectativa é a vinda de Jesus." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-06-30",
      titulo: "MAKING OF",
      conteudo: "Deus enviou juízos sobre Israel porque a nação rejeitou e crucificou o Messias. Os judeus desprezaram a oferta de misericórdia e escolheram ser governados por outro líder – Satanás. Por causa disso, Deus retirou Sua proteção e eles foram entregues aos inimigos (p. 19).\n\nSe a nação de Israel tivesse permanecido fiel a Deus, Jerusalém teria sido preservada como a cidade escolhida. Mas os judeus preferiram a apostasia e a rebelião (p. 16).\n\nO segundo templo (o primeiro foi destruído por Nabucodonosor) foi construído 500 anos antes do nascimento de Cristo. A arca, o propiciatório e as tábuas da lei não estavam mais no lugar santíssimo. Ellen White escreveu que, na época da invasão da Babilônia, homens justos esconderam a arca e seu conteúdo em uma caverna. Ela permanece escondida até hoje (Os Ungidos, p. 195, 196). \n\nNenhum cristão foi morto na destruição de Jerusalém. Quando o general romano retirou seus exércitos sem motivo aparente, as forças judaicas saíram em sua perseguição. Aqueles que acreditaram nas palavras de Jesus reconheceram o sinal (Lc 21:20,21) e conseguiram escapar para um lugar seguro (p. 20).\n\nA terrível maldição lançada pelos judeus a eles mesmos no julgamento de Jesus (Mt 27:25) se cumpriu ao pé da letra. Mais de um milhão de pessoas morreram e os sobreviventes foram levados cativos, vendidos como escravos, jogados às feras nos anfiteatros ou espalhados como peregrinos pela Terra (p. 21, 22).\n\nAo comparar a destruição de Jerusalém com o tempo do fim, Ellen White escreveu: 'Quando o Espírito de Deus, que refreia o mal, for completamente retirado... o mundo verá as consequências do domínio de Satanás como nunca antes' (p. 23).",
      versiculoChave: { texto: "Quando virem Jerusalém cercada de exércitos, fiquem sabendo que a sua destruição está próxima.", referencia: "Lucas 21:20" },
      perguntas: [
        { id: "d4q1", pergunta: "Por que Deus retirou Sua proteção de Israel, segundo o texto?", opcoes: ["Por causa de uma seca", "Porque a nação rejeitou e crucificou o Messias", "Por inveja dos romanos", "Por causa de um terremoto"], correta: 1, explicacao: "Foi porque eles rejeitaram e crucificaram o Messias." },
        { id: "d4q2", pergunta: "O que aconteceu quando o general romano retirou seus exércitos sem motivo aparente?", opcoes: ["Os cristãos foram todos mortos", "Os que reconheceram o sinal conseguiram escapar", "Jerusalém foi reconstruída", "Nada mudou"], correta: 1, explicacao: "Os cristãos que acreditaram nas palavras de Jesus escaparam." },
        { id: "d4q3", pergunta: "Segundo Ellen White, onde a arca da aliança foi escondida?", opcoes: ["Em uma caverna", "No deserto", "No Egito", "Em Roma"], correta: 0, explicacao: "Foi escondida em uma caverna por homens justos." },
        { id: "d4q4", pergunta: "Aproximadamente quantas pessoas morreram na destruição de Jerusalém, segundo o texto?", opcoes: ["Mil", "Cem mil", "Mais de um milhão", "Dez mil"], correta: 2, explicacao: "Mais de um milhão de pessoas morreram." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-01",
      titulo: "EXTRAS",
      conteudo: "A perseguição, como experimentada pelos primeiros cristãos, não existe em nosso país hoje. Às vezes, pensamos que estamos sendo perseguidos quando alguém discorda de nós ou desiste de nos dar um emprego se não pudermos trabalhar aos sábados. Isso é mais precisamente descrito como discriminação religiosa. Mas o tipo de perseguição que os cristãos primitivos enfrentaram foi diferente. Eles encararam a morte.\n\nEm outras partes do mundo, os cristãos ainda enfrentam perseguição em seu sentido mais real. Eles arriscam sua vida e a vida de seus familiares a fim de adorar a Deus. Eles estão dispostos a morrer para obedecer à lei de Deus. Isso é devoção!\n\nReserve um tempo hoje para orar por essas pessoas fiéis.\n\nTextos adicionais: Salmo 50:15; Salmo 116:15; Apocalipse 2:10",
      versiculoChave: { texto: "Não tenhas medo do que irás sofrer... Sê fiel até à morte, e dar-te-ei a coroa da vida.", referencia: "Apocalipse 2:10" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo o texto, o que sofremos hoje quando perdemos um emprego por causa do sábado é mais bem descrito como:", opcoes: ["Perseguição", "Discriminação religiosa", "Injustiça social", "Bullying"], correta: 1, explicacao: "É descrito mais precisamente como discriminação religiosa." },
        { id: "d5q2", pergunta: "Qual destes NÃO está entre os 'textos adicionais' de hoje?", opcoes: ["Salmo 50:15", "Salmo 116:15", "Apocalipse 2:10", "João 3:16"], correta: 3, explicacao: "João 3:16 não está listado." },
        { id: "d5q3", pergunta: "O texto convida você a fazer o quê hoje, em favor dos cristãos perseguidos no mundo?", opcoes: ["Protestar nas redes sociais", "Orar por eles", "Ignorar o assunto", "Escrever ao governo"], correta: 1, explicacao: "Convida a orar por essas pessoas fiéis." },
        { id: "d5q4", pergunta: "Segundo o texto, os cristãos perseguidos em outras partes do mundo estão dispostos a:", opcoes: ["Negociar sua fé", "Morrer para obedecer à lei de Deus", "Esconder sua fé", "Migrar de país"], correta: 1, explicacao: "Estão dispostos a morrer para obedecer à lei de Deus." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-02",
      titulo: "PANORÂMICA",
      conteudo: "Os textos complementares do estudo desta semana estão nos capítulos 1 e 2 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) e estão imperdíveis. Você já leu uma história tão envolvente que se sentiu dentro dela?\n\nO capítulo 1 apresenta uma descrição precisa do cumprimento da profecia feita por Jesus a respeito da destruição de Jerusalém. Os detalhes são impressionantes! No capítulo 2 você tem o quadro chocante da perseguição aos primeiros cristãos, iniciada pelo imperador romano Nero, e a maneira astuciosa como o inimigo trabalhou para introduzir os enganos na igreja.\n\nHá uma luta ferrenha em andamento exatamente agora, e a Bíblia é a única arma que pode impedir que sejamos derrotados. Em nenhuma outra época foi tão necessário conhecer o que Deus revelou em Sua Palavra. Somos os personagens dos últimos capítulos desta história. Como você está se preparando para o confronto final?\n\n'Muitos que são fracos na fé estão prontos para perder a confiança em Deus porque Ele permite que os maus prosperem... Deus nos deixou evidências suficientes de Seu amor. Não devemos duvidar de Sua bondade por sermos incapazes de entender Suas obras...'",
      versiculoChave: { texto: "Não devemos duvidar de Sua bondade por sermos incapazes de entender Suas obras.", referencia: "Os Resgatados" },
      perguntas: [
        { id: "d6q1", pergunta: "Os capítulos complementares desta semana, do livro 'Os Resgatados', são:", opcoes: ["1 e 2", "5 e 6", "10 e 11", "20 e 21"], correta: 0, explicacao: "São os capítulos 1 e 2." },
        { id: "d6q2", pergunta: "Qual imperador romano iniciou a perseguição aos primeiros cristãos, segundo o texto?", opcoes: ["Constantino", "Nero", "Augusto", "Justiniano"], correta: 1, explicacao: "A perseguição foi iniciada por Nero." },
        { id: "d6q3", pergunta: "Segundo a citação do dia, por que Deus permite que os maus prosperem enquanto os justos sofrem?", opcoes: ["Porque Ele não tem poder", "Porque devemos confiar nEle mesmo sem entender tudo", "Porque Ele esqueceu os justos", "O texto não fala disso"], correta: 1, explicacao: "Deus deixou evidências suficientes de Seu amor, devemos confiar." },
        { id: "d6q4", pergunta: "Qual é o outro nome usado para o livro 'Os Resgatados', segundo o texto?", opcoes: ["O Grande Conflito", "Patriarcas e Profetas", "O Desejado de Todas as Nações", "Profetas e Reis"], correta: 0, explicacao: "Também é conhecido como O Grande Conflito." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-03",
      titulo: "OFF",
      conteudo: "Os primeiros cristãos sofreram perseguição intensa. Mas, munidos da força de Deus e da certeza de Sua presença, foram capazes de enfrentar a morte em defesa do que sabiam ser a verdade. Para eles, Deus era real. É muito difícil imaginar enfrentar esse tipo de adversidade por causa de convicções religiosas, mas muitas pessoas em países diferentes sabem muito bem o que isso significa.\n\nNão somos confrontados com o mesmo teste de fé em meio à liberdade que hoje desfrutamos em nosso país, ao adorarmos a Deus da forma como desejamos e enfrentarmos pouca ou nenhuma oposição.\n\nQuão real é Deus para você? Como é sua experiência com Ele? É Deus uma ideia? Um ideal? Um conjunto de regras? Se você não experimentar Deus em sua vida de uma forma real, estará perdendo algo emocionante e poderoso!\n\nALÉM DO ESTUDO: Você já teve a impressão de que o mundo está mais perto da paz do que da perseguição? Veja o que este texto diz sobre parecer que a perseguição está adormecida: 'O único motivo é que a igreja se conformou ao padrão do mundo e, por isso, não desperta oposição' (Os Resgatados, p. 28).",
      versiculoChave: { texto: "o sangue dos cristãos é semente.", referencia: "Tertuliano" },
      perguntas: [
        { id: "d7q1", pergunta: "Quem é o autor da frase 'o sangue dos cristãos é semente'?", opcoes: ["Tertuliano", "Ellen White", "Martinho Lutero", "Paulo"], correta: 0, explicacao: "Foi dita por Tertuliano." },
        { id: "d7q2", pergunta: "Segundo 'Os Resgatados', por que a perseguição parece 'adormecida' hoje?", opcoes: ["Porque o mundo melhorou", "Porque a igreja se conformou ao padrão do mundo e não desperta oposição", "Porque não há mais maldade", "Porque Satanás desistiu"], correta: 1, explicacao: "Porque a igreja se conformou ao padrão do mundo." },
        { id: "d7q3", pergunta: "O texto de hoje pergunta: quão real é _____ para você?", opcoes: ["o dinheiro", "Deus", "a igreja", "o sábado"], correta: 1, explicacao: "Quão real é Deus para você?" },
        { id: "d7q4", pergunta: "Na seção 'Além do Estudo', quais capítulos de 'Os Resgatados' são sugeridos?", opcoes: ["1 e 2", "3 e 4", "7 e 8", "11 e 12"], correta: 0, explicacao: "Os capítulos 1 e 2." }
      ]
    }
  ]
};

export const LICOES = [DEMO, PROVADO_PELO_FOGO];
