export const LICAO_2 = {
  titulo: "Lição 2 - Leis Naturais (4 a 10 de julho)",
  semana: "2026-W27",
  trimestre: "Provado pelo Fogo",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-07-04",
      titulo: "TEASER",
      conteudo: "A Idade Média foi um período terrível para qualquer um que pensasse diferente ou questionasse a autoridade vigente na época. A Igreja Católica controlava os reis e as rainhas, os plebeus e os servos. Qualquer opinião diferente daquela imposta pela igreja era totalmente proibida e os 'hereges' eram literalmente caçados, cruelmente torturados e executados pelo crime do pensamento independente.\n\nA igreja havia decretado que unicamente os padres tinham permissão de ler a Bíblia e que o povo entraria em contato com o conteúdo da Palavra de Deus somente por meio desses líderes espirituais. O povo não tinha permissão para ler a Bíblia por si mesmo e tirar as próprias conclusões. A Igreja Católica tornou a religião tão complicada e 'pesada' que as pessoas comuns não conseguiam mais entender que a salvação era um dom gratuito de Deus. A Igreja Romana permitiu que influências pagãs se infiltrassem em sua doutrina, fazendo com que até mesmo a lei de Deus parecesse ter sido mudada.\n\nMas Deus não permitiu que Sua Palavra fosse alterada. Ele sempre teve um pequeno povo remanescente que protegeu as Escrituras e ensinou os preceitos divinos aos seus descendentes. Os valdenses são um exemplo desse povo. Eles foram obrigados a viver escondidos e sofreram muitas perseguições, mas guardaram fiel e cuidadosamente a Palavra de Deus. Ainda hoje Deus tem um povo remanescente que, da mesma forma, valoriza e obedece à Sua Palavra.",
      versiculoChave: { texto: "Porque o mistério da iniquidade já opera e aguarda somente que seja afastado aquele que agora o detém.", referencia: "2 Tessalonicenses 2:7" },
      perguntas: [
        { id: "d1q1", pergunta: "Na Idade Média, quem tinha permissão de ler a Bíblia, segundo a igreja da época?", opcoes: ["Todo o povo", "Somente os padres", "Somente os reis", "Ninguém"], correta: 1, explicacao: "A igreja havia decretado que unicamente os padres tinham permissão de ler a Bíblia." },
        { id: "d1q2", pergunta: "Quem são os valdenses, citados no texto?", opcoes: ["Um grupo que negava a Bíblia", "Um povo remanescente que protegeu fielmente as Escrituras", "Um exército romano", "Uma seita pagã"], correta: 1, explicacao: "Os valdenses guardaram fiel e cuidadosamente a Palavra de Deus." },
        { id: "d1q3", pergunta: "O que a Igreja Católica permitiu se infiltrar em sua doutrina, segundo o texto?", opcoes: ["Ciência moderna", "Influências pagãs", "Filosofia grega", "Costumes judaicos"], correta: 1, explicacao: "Permitiu que influências pagãs se infiltrassem em sua doutrina." },
        { id: "d1q4", pergunta: "Mesmo na perseguição, o que Deus sempre teve, segundo o texto?", opcoes: ["Um exército poderoso", "Um pequeno povo remanescente fiel", "Um império aliado", "Riquezas escondidas"], correta: 1, explicacao: "Deus sempre teve um pequeno povo remanescente fiel." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-07-05",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Responda rapidinho: Você sabe onde está sua Bíblia neste momento? Ela é importante para você? Que papel a Bíblia desempenha em sua vida?\n\nPegue-a e leia, com atenção, as passagens de Daniel 7:25; 2 Tessalonicenses 2:3-7 e Apocalipse 12:6. Os textos bíblicos para o estudo desta semana revelam quais seriam as estratégias que o inimigo usaria para tentar afastar as pessoas da verdade e destruir o povo de Deus. Depois da leitura, responda às perguntas a seguir:\n\n- Como essas passagens descrevem a Idade Média da história europeia?\n- Quando uma organização religiosa reivindica para si o mesmo poder do próprio Deus, que efeito isso tem sobre as pessoas?\n- Por que Deus nos revelou com antecedência que essas coisas aconteceriam?\n- O que você acha que significa o 'mistério da iniquidade'?\n- O que seriam 'os tempos e as leis' que esse poder tentaria mudar?\n- É possível existir uma organização que tenha começado com intenções puras, tenha se corrompido com o poder, mas ainda abrigue pessoas boas e tementes a Deus? Explique.",
      versiculoChave: { texto: "Pegue sua Bíblia e leia Daniel 7:25; 2 Tessalonicenses 2:3-7 e Apocalipse 12:6", referencia: "Roteiro Original" },
      perguntas: [
        { id: "d2q1", pergunta: "Qual destes textos NÃO foi indicado para leitura hoje?", opcoes: ["Daniel 7:25", "2 Tessalonicenses 2:3-7", "Apocalipse 12:6", "Gênesis 1:1"], correta: 3, explicacao: "Gênesis 1:1 não foi indicado." },
        { id: "d2q2", pergunta: "O 'mistério da iniquidade' é uma expressão encontrada em:", opcoes: ["Daniel", "2 Tessalonicenses", "Apocalipse", "Mateus"], correta: 1, explicacao: "Encontra-se em 2 Tessalonicenses." },
        { id: "d2q3", pergunta: "Segundo o roteiro, o que esse poder profetizado tentaria mudar?", opcoes: ["A capital do império", "Os tempos e as leis", "O calendário romano", "A moeda"], correta: 1, explicacao: "Tentaria mudar os tempos e as leis." },
        { id: "d2q4", pergunta: "O texto pergunta se é possível que uma organização religiosa:", opcoes: ["Comece pura e se corrompa com o poder, mas ainda tenha gente boa", "Seja sempre perfeita", "Nunca erre", "Seja proibida de existir"], correta: 0, explicacao: "Se pode corromper-se mas ainda abrigar pessoas boas e tementes a Deus." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-07-06",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana, que se encontra em 2 Tessalonicenses 2:7. O que é o 'mistério da iniquidade' a que o texto se refere?\n\nO Comentário Bíblico Adventista (vol. 7, p. 277) dá uma boa ajuda na interpretação. Veja o que diz: 'O título se refere a um poder caracterizado pela desobediência. A referência à lei é significativa, em vista da tentativa de mudança da lei mencionada em Daniel 7:25 ['ele falará contra o Altíssimo, oprimirá os Seus santos e tentará mudar os tempos e as leis']. Em última análise, esta descrição se aplica a Satanás, o autor da desobediência, mas o demônio geralmente camufla sua personalidade ao trabalhar por meio de agentes. Nos últimos dias, ele desempenhará um papel mais direto, levando o engano ao cúmulo de falsificar pessoalmente a vinda de Cristo.'\n\nO inimigo conseguirá enganar muita gente porque ele tem trabalhado incessantemente para apagar a imagem de Deus da vida das pessoas. Esse é o primeiro passo. Elas ficarão tão insensíveis que não conseguirão discernir o que estará acontecendo. Confiarão em si mesmas e não serão capazes de enxergar o erro. A Bíblia terá deixado de fazer parte da vida delas por muito tempo, e o conhecimento que poderia salvá-las estará esquecido. A lei de Deus, que é a representação do Seu caráter, simplesmente não fará sentido algum para elas.",
      versiculoChave: { texto: "ele falará contra o Altíssimo, oprimirá os Seus santos e tentará mudar os tempos e as leis", referencia: "Daniel 7:25" },
      perguntas: [
        { id: "d3q1", pergunta: "Qual é o primeiro passo do inimigo para enganar as pessoas, segundo o texto?", opcoes: ["Criar novas religiões", "Apagar a imagem de Deus da vida das pessoas", "Proibir a Bíblia", "Destruir igrejas"], correta: 1, explicacao: "Apagar a imagem de Deus da vida das pessoas." },
        { id: "d3q2", pergunta: "A frase 'as regras foram feitas para serem quebradas' é descrita no texto (contexto geral) como:", opcoes: ["Sábia", "Inofensiva", "Muito perigosa", "Bíblica"], correta: 2, explicacao: "É muito perigosa." },
        { id: "d3q3", pergunta: "Segundo Daniel 7:25, o poder profetizado tentaria mudar os tempos e as:", opcoes: ["Fronteiras", "Moedas", "Leis", "Línguas"], correta: 2, explicacao: "Mudar os tempos e as leis." },
        { id: "d3q4", pergunta: "O Comentário Bíblico Adventista relaciona, em última análise, essa descrição a:", opcoes: ["Satanás", "Roma antiga", "Os judeus", "Os romanos"], correta: 0, explicacao: "Aplica-se a Satanás." }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-07-07",
      titulo: "MAKING OF",
      conteudo: "A apostasia que o apóstolo Paulo menciona em 2 Tessalonicenses 2:3 está ligada ao compromisso que o cristianismo acabou assumindo com o paganismo. Aquilo que Satanás não conseguiu com a perseguição aos cristãos foi conseguido com a sutil introdução de costumes pagãos. Quando o imperador Constantino supostamente se converteu ao cristianismo, muitas das doutrinas e superstições foram misturadas à fé dos seguidores de Cristo.\n\nFoi o imperador Constantino que proclamou um decreto transformando o domingo em uma festa pública em todo o império romano. Os pagãos adoravam o sol nesse dia e os cristãos passaram a honrá-lo como o dia da ressurreição de Jesus. Nessa época, um grupo continuou a observar o sábado como dia de guarda.\n\nO quarto é o único mandamento que aponta para Deus como Criador. Por isso Satanás tem direcionado seus esforços contra ele. Atualmente ele tem usado outros métodos para tirar Deus da vida das pessoas. Tem ensinado que cada um deve buscar ser feliz à sua maneira, seguindo o que o coração diz, sem levar em conta as orientações e as leis divinas.\n\nO papado fez sérias mudanças na lei de Deus. Substituiu a adoração de ídolos pela adoração de imagens (dos santos) e de relíquias (objetos considerados sagrados) e mexeu no quarto mandamento, anulando o sábado e exaltando o domingo como dia de guarda.\n\nOs cristãos valdenses basearam sua fé apenas na Bíblia. Eles tinham o costume de copiar porções da Bíblia e usá-las para espalhar a mensagem de salvação.",
      versiculoChave: { texto: "Foi o imperador Constantino que proclamou um decreto transformando o domingo em uma festa pública...", referencia: "Fato Histórico" },
      perguntas: [
        { id: "d4q1", pergunta: "Qual imperador transformou o domingo em festa pública no império romano?", opcoes: ["Nero", "Constantino", "Justiniano", "Diocleciano"], correta: 1, explicacao: "Constantino proclamou esse decreto." },
        { id: "d4q2", pergunta: "Qual é o único mandamento que aponta para Deus como Criador, segundo o texto?", opcoes: ["O primeiro", "O quarto", "O sexto", "O décimo"], correta: 1, explicacao: "O quarto mandamento." },
        { id: "d4q3", pergunta: "Segundo o texto, quem o papado afirmou ser na Terra?", opcoes: ["Um simples servo dos cristãos", "O governante designado por Deus", "Um simples bispo", "Um conselheiro do imperador"], correta: 1, explicacao: "O governante designado por Deus." },
        { id: "d4q4", pergunta: "O que os valdenses costumavam fazer para espalhar a Palavra de Deus?", opcoes: ["Pregar em praças públicas", "Copiar porções da Bíblia", "Imprimir jornais", "Construir templos"], correta: 1, explicacao: "Eles copiavam porções da Bíblia." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-08",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Uma crença comum por aí é que, após a morte de Jesus na cruz, a lei de Deus deixou de ser importante. Pelo que você viu nos textos bíblicos, isso aconteceu de fato? Na verdade, existem promessas de que nossa vida será mais abençoada e mais feliz por seguirmos a direção de Deus. Confira os Dez Mandamentos em Êxodo 20. Há alguma lei de Deus que você acha que não seja importante hoje?\n\nPense na sociedade atual. Qual a função das leis?\n\nA lei de Deus serve de proteção para que possamos exercer nossa liberdade da forma correta. Lembre-se de que, no fim dos tempos, as pessoas farão parte de apenas dois grupos: os que guardam a lei de Deus e acreditam no testemunho de Jesus e os que não o fazem. Por meio de suas atitudes e escolhas hoje, a que grupo você está se preparando para pertencer?\n\nTextos adicionais: Salmo 119:105; Levítico 24:22; Mateus 5:17,18",
      versiculoChave: { texto: "Não pensem que vim abolir a Lei ou os Profetas; não vim abolir, mas cumprir.", referencia: "Mateus 5:17" },
      perguntas: [
        { id: "d5q1", pergunta: "Onde encontramos os Dez Mandamentos, citados no texto de hoje?", opcoes: ["Êxodo 20", "Gênesis 1", "Mateus 5", "Apocalipse 14"], correta: 0, explicacao: "Estão em Êxodo 20." },
        { id: "d5q2", pergunta: "Segundo o texto, no fim dos tempos as pessoas farão parte de quantos grupos?", opcoes: ["Um", "Dois", "Três", "Quatro"], correta: 1, explicacao: "Apenas dois grupos." },
        { id: "d5q3", pergunta: "Qual destes é um dos 'textos adicionais' desta semana?", opcoes: ["Salmo 119:105", "João 3:16", "Romanos 8:1", "Gênesis 3:15"], correta: 0, explicacao: "Salmo 119:105." },
        { id: "d5q4", pergunta: "Segundo o texto, a lei de Deus serve para:", opcoes: ["Limitar nossa liberdade injustamente", "Proteger o exercício correto da liberdade", "Nada, ela é obsoleta", "Apenas os judeus"], correta: 1, explicacao: "Proteger o exercício correto da liberdade." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-09",
      titulo: "PANORÂMICA",
      conteudo: "Os capítulos 3 e 4 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) são um convite para entendermos como algumas profecias de Daniel tiveram cumprimento ao longo da história e como Satanás trabalhou incansavelmente para que as pessoas não tivessem acesso à Bíblia. Quanto mais difícil era o acesso à Palavra de Deus, mais ela era desejada e valorizada pelos seguidores de Cristo. Os valdenses, por exemplo, ficaram conhecidos por copiar cuidadosamente porções da Bíblia e usá-las para espalhar a mensagem da salvação em um tempo de muita perseguição.\n\nHoje, a maioria das pessoas tem muitas Bíblias em casa. Há tantas versões diferentes da Bíblia disponíveis até na internet. Existem aplicativos da Bíblia. Mas será que, com tanta facilidade atualmente, a Bíblia tem sido tratada com o devido respeito, como a confiável Palavra de Deus, o guia seguro para a vida? Imagine se todas as Bíblias fossem retiradas e as pessoas fossem impedidas de lê-la, qual seria a sua reação? Você sentiria falta dela?\n\n'Satanás sabia muito bem que foram as Sagradas Escrituras que capacitaram o Salvador a resistir a seus ataques. A cada investida, Cristo lhe apresentava o escudo da verdade eterna, dizendo: 'Está escrito'. Para que Satanás mantenha seu controle sobre o povo e estabeleça a autoridade do usurpador papal, ele deve manter as pessoas em ignorância quanto à Bíblia. Precisa esconder e suprimir as sagradas verdades.' (Os Resgatados, p. 30)",
      versiculoChave: { texto: "Cristo lhe apresentava o escudo da verdade eterna, dizendo: 'Está escrito'.", referencia: "Os Resgatados" },
      perguntas: [
        { id: "d6q1", pergunta: "Os capítulos complementares desta semana são:", opcoes: ["1 e 2", "3 e 4", "5 e 6", "9 e 10"], correta: 1, explicacao: "São os capítulos 3 e 4." },
        { id: "d6q2", pergunta: "O texto pergunta: apesar de termos tantas Bíblias hoje, será que ela é tratada com:", opcoes: ["O devido respeito", "Indiferença total", "Ódio", "Medo"], correta: 0, explicacao: "O devido respeito." },
        { id: "d6q3", pergunta: "Segundo a citação de 'Os Resgatados', o que Satanás precisa fazer para manter seu controle sobre o povo?", opcoes: ["Construir templos", "Manter as pessoas em ignorância quanto à Bíblia", "Criar novas leis", "Aumentar impostos"], correta: 1, explicacao: "Manter as pessoas em ignorância quanto à Bíblia." },
        { id: "d6q4", pergunta: "Qual arma Cristo usou contra Satanás no deserto, segundo a citação?", opcoes: ["A oração apenas", "O escudo da verdade eterna, dizendo 'Está escrito'", "Um anjo guardião", "Jejum apenas"], correta: 1, explicacao: "O escudo da verdade eterna." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-10",
      titulo: "OFF",
      conteudo: "Na Idade Média, as pessoas não tinham acesso à Bíblia; tinham, no entanto, consciência de seu valor. Quando tentavam ter acesso a ela, eram perseguidos e geralmente mortos. Esse foi um período aterrorizador para os fiéis seguidores de Deus. Nessa época, porém, Deus não permitiu que Sua Palavra desaparecesse totalmente. Ele sempre manteve um povo remanescente que protegeu Sua Santa Palavra.\n\nA Bíblia dá poder aos fiéis. Nela encontramos promessas, esperança, orientações e instruções. Hoje, a maioria de nós possui livre acesso à Bíblia em qualquer idioma ou versão desejada, e com isso nos esquecemos do verdadeiro valor da Palavra de Deus. A familiaridade gerou desprezo. Mas, se olharmos para o passado e considerarmos as experiências daqueles que viveram durante a Idade Média, vamos nos lembrar da razão de a Bíblia ser digna de darmos a vida por ela.\n\n'Assim como a arca sobre as águas agitadas, a Palavra de Deus supera as tempestades que ameaçam sua destruição. Como uma mina com ricos veios de ouro e prata escondidos debaixo da superfície, as Sagradas Escrituras contêm tesouros da verdade que somente aquele que busca com humildade e oração pode encontrar' (Os Resgatados, p. 40).\n\nALÉM DO ESTUDO: Como você e seus amigos consideram a Bíblia? Você tem separado diariamente um momento para estudar a Palavra de Deus? Leia o que Paulo escreveu para o jovem Timóteo: 'Toda a Escritura é inspirada por Deus...' (2 Timóteo 3:16, NVT). Acesse os capítulos 3 e 4 do livro Os Resgatados.",
      versiculoChave: { texto: "O poder não corrompe. O medo corrompe... Talvez o medo de perder o poder.", referencia: "João Steinbeck" },
      perguntas: [
        { id: "d7q1", pergunta: "Segundo o texto, o que a familiaridade com a Bíblia pode gerar, infelizmente?", opcoes: ["Mais amor por ela", "Desprezo", "Mais estudo", "Nada muda"], correta: 1, explicacao: "A familiaridade gerou desprezo." },
        { id: "d7q2", pergunta: "Qual versículo de 2 Timóteo é citado na seção 'Além do Estudo'?", opcoes: ["2 Timóteo 3:15", "2 Timóteo 3:16", "2 Timóteo 4:1", "2 Timóteo 1:7"], correta: 1, explicacao: "2 Timóteo 3:16." },
        { id: "d7q3", pergunta: "A Palavra de Deus é comparada a quê na citação de 'Os Resgatados'?", opcoes: ["Uma mina com ricos veios de ouro e prata", "Um rio seco", "Uma pedra fria", "Um livro comum"], correta: 0, explicacao: "Uma mina com ricos veios de ouro e prata." },
        { id: "d7q4", pergunta: "Quem disse a frase 'O poder não corrompe. O medo corrompe...'?", opcoes: ["Graham Greene", "João Steinbeck", "Ellen White", "Tertuliano"], correta: 1, explicacao: "Foi João Steinbeck." }
      ]
    }
  ]
};

export const LICAO_3 = {
  titulo: "Lição 3 - Luz que Ilumina o Caminho (11 a 17 de julho)",
  semana: "2026-W28",
  trimestre: "Provado pelo Fogo",
  dias: [
    {
      id: 1, diaSemana: "Sáb", data: "2026-07-11",
      titulo: "TEASER",
      conteudo: "Esta lição oferece a oportunidade de conhecermos um pouco mais a respeito da Palavra de Deus. A Bíblia não é uma coleção de histórias inúteis. Trata-se de histórias de amor, palavras de conforto e esperança, autobiografias e biografias, profecias, instruções e um conjunto de cartas inspiradas pelo próprio Deus. Tudo isso em um único livro!\n\nNas palavras de Franky Schaeffer: 'Deus nos deu em forma escrita um livro que engloba todas as emoções humanas, os altos, os baixos, a diversidade de indivíduos, o bem e o mal, o feio, o bonito, os pecadores, os justos, os perversos, os salvos, os perdidos, a poesia, os poetas, a sabedoria, o sábio, histórias humanas, a realidade da vida, abundante em significado, um livro da verdade, não de dizeres religiosos pálidos e limitados. A Bíblia, a Palavra de Deus, é sólida, humana, comprovável, realmente divina.'\n\nConsiderar a Palavra de Deus como 'realmente divina' nos ajuda a entender por que homens como Wycliffe, Huss e Jerônimo se dispuseram a dar a própria vida por ela. Eles suportaram torturas inimagináveis porque compreenderam que a Bíblia é mais do que um bom livro de história ou uma coleção de provérbios; é, sim, a fonte da vida. Ao estudar a lição desta semana, tire o máximo proveito do conteúdo e coloque a Bíblia no lugar que ela merece ter em sua vida.",
      versiculoChave: { texto: "Tua palavra é lâmpada para meus pés e luz para meu caminho.", referencia: "Salmo 119:105" },
      perguntas: [
        { id: "d1q1", pergunta: "Segundo Franky Schaeffer, a Bíblia é um livro:", opcoes: ["Religioso e limitado", "Sólido, humano, comprovável, realmente divino", "Só de regras", "Difícil de entender"], correta: 1, explicacao: "A Bíblia, a Palavra de Deus, é sólida, humana, comprovável, realmente divina." },
        { id: "d1q2", pergunta: "Quais três reformadores são citados como exemplos de quem deu a vida pela Bíblia?", opcoes: ["Lutero, Calvino e Zuínglio", "Wycliffe, Huss e Jerônimo", "Pedro, Paulo e João", "Moisés, Davi e Daniel"], correta: 1, explicacao: "Wycliffe, Huss e Jerônimo se dispuseram a dar a própria vida por ela." },
        { id: "d1q3", pergunta: "A Bíblia é descrita no texto como, na verdade:", opcoes: ["Um livro de poesia", "A fonte da vida", "Um manual de regras", "Uma coleção de mitos"], correta: 1, explicacao: "É, sim, a fonte da vida." },
        { id: "d1q4", pergunta: "O texto-chave da semana é:", opcoes: ["Salmo 23", "Salmo 119:105", "Salmo 91", "Salmo 51"], correta: 1, explicacao: "O texto chave é Salmo 119:105." }
      ]
    },
    {
      id: 2, diaSemana: "Dom", data: "2026-07-12",
      titulo: "ROTEIRO ORIGINAL",
      conteudo: "Apesar de constar no Guinness como um dos livros mais vendidos de todos os tempos, a Bíblia não está na lista dos mais lidos nos últimos anos. O que você acha que essa informação revela? Leia em sua Bíblia os textos de Salmo 119:105 e Mateus 10:17-22. Depois, responda às perguntas a seguir:\n\nCompare o Salmo 119:105 com os seguintes versos:\n- Provérbios 30:5\n- Lucas 11:28\n- 2 Timóteo 3:15,16\n- Hebreus 4:12\n\n- Qual é o tema principal que se sobressai nos cinco textos?\n- O que esses versos lhe dizem particularmente?\n- Como você pode ser beneficiado se aumentar o tempo que passa lendo a Bíblia?\n- Como o contexto da história de Jesus enviando os doze discípulos esclarece os versos 17-22 de Mateus 10?\n- Essa passagem é mais, menos ou igualmente relevante para os seguidores de Jesus hoje? Explique.\n- Como as inevitáveis provações sobre as quais Jesus nos advertiu podem causar impacto na fé manifestada por uma pessoa?",
      versiculoChave: { texto: "Compare Salmo 119:105 com Provérbios 30:5, Lucas 11:28, 2 Timóteo 3:15,16, Hebreus 4:12", referencia: "Textos de Estudo" },
      perguntas: [
        { id: "d2q1", pergunta: "Apesar de ser um dos livros mais vendidos, a Bíblia não está entre os mais:", opcoes: ["Vendidos", "Lidos atualmente", "Traduzidos", "Comprados"], correta: 1, explicacao: "A Bíblia não está na lista dos mais lidos nos últimos anos." },
        { id: "d2q2", pergunta: "Qual destes NÃO foi citado para comparação com o Salmo 119:105?", opcoes: ["Provérbios 30:5", "Lucas 11:28", "Hebreus 4:12", "Apocalipse 1:1"], correta: 3, explicacao: "Apocalipse 1:1 não foi citado." },
        { id: "d2q3", pergunta: "Em Mateus 10:17-22, Jesus estava enviando:", opcoes: ["Os doze discípulos", "Os profetas do AT", "Os anjos", "Os fariseus"], correta: 0, explicacao: "Jesus estava enviando os doze discípulos." },
        { id: "d2q4", pergunta: "O tema principal que se sobressai nos cinco textos lidos hoje é:", opcoes: ["A importância da oração", "O valor e o poder da Palavra de Deus", "O juízo final", "A criação do mundo"], correta: 1, explicacao: "O valor e o poder da Palavra de Deus." }
      ]
    },
    {
      id: 3, diaSemana: "Seg", data: "2026-07-13",
      titulo: "ZOOM",
      conteudo: "Leia o Texto-Chave desta semana. É um dos versos mais conhecidos da Bíblia e se encontra no Salmo 119:105.\n\nVeja que interessante aplicação para esse verso: Para andar com segurança na floresta à noite, precisamos de uma luz a fim de que não tropecemos nas raízes das árvores ou caiamos em buracos. Nesta vida, andamos pela floresta escura do mal. Mas a Bíblia pode ser nossa luz para nos mostrar o caminho à frente, para que não tropecemos ao caminharmos. Ela revela as raízes emaranhadas dos valores e filosofias. Estude a Bíblia e você será capaz de ver seu caminho claramente, o suficiente para permanecer na direção certa (Life Application Bible).\n\nHoje há muitas vozes defendendo pontos de vistas estranhos. A maioria quer convencer com argumentos e gritos. Não importa o tempo em que foi escrita, a Bíblia continua sendo nossa única proteção contra os enganos.\n\nComo escreveu Ellen White: 'Deus conduz Seus seguidores à Bíblia como sua única proteção contra o poder dos espíritos maus. Satanás usa toda estratégia possível para impedir que as pessoas obtenham conhecimento da Bíblia... A falsificação será tão parecida com o verdadeiro que será impossível identificar a diferença entre ambos, a não ser pelas Escrituras' (Os Resgatados, p. 301).\n\nAgora é o tempo para conhecermos profundamente o que a Bíblia diz. Ela deve ser nossa regra de fé!",
      versiculoChave: { texto: "A falsificação será tão parecida com o verdadeiro que será impossível identificar a diferença... a não ser pelas Escrituras.", referencia: "Os Resgatados" },
      perguntas: [
        { id: "d3q1", pergunta: "A ilustração usada hoje compara a Bíblia a uma luz para andar em qual ambiente?", opcoes: ["Uma estrada deserta", "Uma floresta à noite", "Um oceano", "Um deserto"], correta: 1, explicacao: "Para andar com segurança na floresta à noite." },
        { id: "d3q2", pergunta: "Segundo Ellen White, qual é a única proteção segura contra os enganos finais?", opcoes: ["A intuição", "As Escrituras", "A tradição", "A ciência"], correta: 1, explicacao: "A Bíblia como única proteção." },
        { id: "d3q3", pergunta: "O texto afirma que a falsificação no fim dos tempos será:", opcoes: ["Fácil de identificar", "Tão parecida com o verdadeiro que será quase impossível distinguir, exceto pelas Escrituras", "Inexistente", "Apenas teórica"], correta: 1, explicacao: "Impossível de distinguir, a não ser pelas Escrituras." },
        { id: "d3q4", pergunta: "A Bíblia deve ser, segundo o texto de hoje, nossa:", opcoes: ["Opção entre várias", "Regra de fé", "Curiosidade histórica", "Última escolha"], correta: 1, explicacao: "Ela deve ser nossa regra de fé!" }
      ]
    },
    {
      id: 4, diaSemana: "Ter", data: "2026-07-14",
      titulo: "MAKING OF",
      conteudo: "John Huss: Nasceu em um lar humilde na Boêmia. Estudou na Universidade de Praga e entrou para o sacerdócio. Tornou-se professor e depois reitor da universidade. Ao estudar a Bíblia e os escritos de Wycliffe reconheceu o verdadeiro caráter do papado e denunciou o orgulho, a ambição e a corrupção da hierarquia. Foi condenado a morrer queimado na estaca. Morreu cantando. Suas cinzas foram lançadas no Reno, de onde seguiram para o oceano, como sementes espalhadas para o mundo.\n\nJohn Wycliffe: Viveu no século 14, na Inglaterra. Ficou conhecido como 'a estrela da manhã da Reforma'. Estudou teologia e se tornou capelão do rei. Corajosamente se posicionou contra a Igreja de Roma porque ela havia abandonado a Palavra de Deus. Era um pregador habilidoso e eloquente, que vivia as verdades que pregava. A maior obra de sua vida foi a tradução das Escrituras para o inglês. Seu objetivo era que todos da Inglaterra pudessem ler sobre as obras maravilhosas de Deus. Ensinou que o Espírito Santo era o único intérprete da Bíblia.\n\nJerônimo: Nasceu em Praga. Estudou na Universidade de Oxford, na Inglaterra, local em que adotou as doutrinas de John Wycliffe. Ao retornar a Praga em 1407, associou-se a John Huss e passou a pregar contra os abusos da hierarquia da igreja e da corrupção e depravação do clero. Na ocasião em que Huss foi denunciado pelo Concílio de Constança e preso, Jerônimo apressou-se para Constança para defender o amigo, mas, ao saber que também seria condenado, tentou retornar para Praga. Foi preso na Bavária e retornou a Constança, ocasião em que renunciou às suas crenças. Mais tarde, arrependeu-se de sua renúncia e foi queimado vivo como herege.",
      versiculoChave: { texto: "John Wycliffe ficou conhecido como 'a estrela da manhã da Reforma'.", referencia: "História" },
      perguntas: [
        { id: "d4q1", pergunta: "John Huss estudou em qual universidade?", opcoes: ["Oxford", "Praga", "Paris", "Wittenberg"], correta: 1, explicacao: "Estudou na Universidade de Praga." },
        { id: "d4q2", pergunta: "Como John Huss morreu, segundo o texto?", opcoes: ["De doença", "Queimado na estaca, cantando", "Em batalha", "De velhice"], correta: 1, explicacao: "Foi condenado a morrer queimado na estaca, cantando." },
        { id: "d4q3", pergunta: "John Wycliffe é conhecido como:", opcoes: ["'O pai da Reforma'", "'A estrela da manhã da Reforma'", "'O mártir silencioso'", "'O doutor da igreja'"], correta: 1, explicacao: "A estrela da manhã da Reforma." },
        { id: "d4q4", pergunta: "Qual foi a maior obra da vida de Wycliffe?", opcoes: ["Construir uma universidade", "Traduzir as Escrituras para o inglês", "Fundar uma igreja", "Escrever um hino"], correta: 1, explicacao: "A tradução das Escrituras para o inglês." }
      ]
    },
    {
      id: 5, diaSemana: "Qua", data: "2026-07-15",
      titulo: "EXTRAS",
      conteudo: "Leia e marque em sua Bíblia os textos adicionais desta semana. Uma pesquisa realizada pelo Instituto Americano de Cultura e Fé revelou que a maioria das pessoas que se identificam como cristãs não conhece a visão da Bíblia Sagrada sobre assuntos do dia a dia e princípios morais que devem ser aplicados à vida. Das seis mil pessoas entrevistadas, apenas 14% souberam responder a questões básicas ligadas à fé que professam. Alarmante!\n\nApesar de 76% acreditarem que a Bíblia é a verdadeira Palavra de Deus e sete pessoas em cada dez concordarem que ela é totalmente precisa nos princípios de vida que ensina, menos da metade dos entrevistados (46%) disseram ler a Bíblia pelo menos uma vez por semana. Isso explica por que as pessoas estão cada vez mais distantes do ensino bíblico. De acordo com os pesquisadores, esse levantamento expõe um imenso abismo entre se identificar como cristão e viver como um seguidor de Jesus.\n\nQuantas vezes por semana você costuma ler a Bíblia? Faça uma experiência: leia pelo menos um capítulo da Bíblia por dia e observe a diferença que isso vai fazer em sua vida.\n\nTextos adicionais: Josué 1:8,9; Lucas 11:28; Efésios 6:13-18",
      versiculoChave: { texto: "Não se aparte da tua boca o livro desta lei; antes medita nele dia e noite...", referencia: "Josué 1:8" },
      perguntas: [
        { id: "d5q1", pergunta: "Segundo a pesquisa citada, que porcentagem dos entrevistados soube responder questões básicas da fé?", opcoes: ["76%", "46%", "14%", "90%"], correta: 2, explicacao: "Apenas 14% souberam responder." },
        { id: "d5q2", pergunta: "Qual porcentagem acreditava que a Bíblia é a verdadeira Palavra de Deus, segundo a pesquisa?", opcoes: ["14%", "46%", "76%", "100%"], correta: 2, explicacao: "76% acreditam que a Bíblia é a Palavra de Deus." },
        { id: "d5q3", pergunta: "Que porcentagem disse ler a Bíblia ao menos uma vez por semana?", opcoes: ["14%", "46%", "76%", "30%"], correta: 1, explicacao: "Menos da metade dos entrevistados (46%)." },
        { id: "d5q4", pergunta: "O que essa pesquisa expõe, segundo o texto?", opcoes: ["Que todos seguem a Bíblia fielmente", "Um abismo entre se identificar como cristão e viver como seguidor de Jesus", "Que a Bíblia é desnecessária", "Que ninguém lê a Bíblia"], correta: 1, explicacao: "Um imenso abismo entre se identificar como cristão e viver como um seguidor de Jesus." }
      ]
    },
    {
      id: 6, diaSemana: "Qui", data: "2026-07-16",
      titulo: "PANORÂMICA",
      conteudo: "Leia os capítulos 5 e 6 do livro Os Resgatados (O Grande Conflito na linguagem de hoje) para saber como a luz do evangelho chegou à Inglaterra e ainda conhecer a história de dois heróis que enfrentaram a morte para defender o acesso das pessoas à Bíblia. Você descobriu a quem o texto ao lado se refere?\n\nVeja como Ellen White descreveu as Sagradas Escrituras: 'A Bíblia é uma transcrição da vontade de Deus, uma expressão da sabedoria divina. Ela guiará todos os que obedecerem aos seus ensinos, impedindo-os de desperdiçar sua vida em um esforço mal orientado' (Os Embaixadores, p. 234).\n\nO ser humano não pode encontrar verdadeira felicidade se estiver fora dos planos e da vontade de Deus para sua vida. A Bíblia é o único guia seguro na viagem rumo ao Céu. É a mais poderosa arma contra os enganos do inimigo. É o 'agente designado pelo Céu para libertar, esclarecer e evangelizar as pessoas' (Os Resgatados, p. 49).\n\n'Pureza de vida, diligência constante em estudo e labores, integridade incorruptível e amor cristão caracterizaram o primeiro dos reformadores. Foi a Bíblia quem o fez assim. O estudo das Escrituras enobrece cada pensamento, sentimento e ambição, de uma forma que nenhum outro estudo é capaz de fazer. Dá firmeza de propósito, coragem e força...'",
      versiculoChave: { texto: "O estudo das Escrituras enobrece cada pensamento... Dá firmeza de propósito, coragem e força.", referencia: "Os Resgatados" },
      perguntas: [
        { id: "d6q1", pergunta: "Os capítulos complementares de hoje tratam de como a luz do evangelho chegou a:", opcoes: ["França", "Inglaterra", "Alemanha", "Espanha"], correta: 1, explicacao: "Como a luz do evangelho chegou à Inglaterra." },
        { id: "d6q2", pergunta: "Segundo Ellen White, a Bíblia é uma transcrição de quê?", opcoes: ["Da vontade de Deus", "Das tradições humanas", "Da cultura judaica", "Da filosofia grega"], correta: 0, explicacao: "Uma transcrição da vontade de Deus." },
        { id: "d6q3", pergunta: "A Bíblia é chamada no texto de 'agente designado pelo Céu' para:", opcoes: ["Julgar as nações", "Libertar, esclarecer e evangelizar as pessoas", "Construir templos", "Definir leis civis"], correta: 1, explicacao: "Libertar, esclarecer e evangelizar as pessoas." },
        { id: "d6q4", pergunta: "O estudo das Escrituras, segundo a citação de hoje, dá ao cristão:", opcoes: ["Riqueza material", "Firmeza de propósito, coragem e força", "Fama", "Poder político"], correta: 1, explicacao: "Dá firmeza de propósito, coragem e força." }
      ]
    },
    {
      id: 7, diaSemana: "Sex", data: "2026-07-17",
      titulo: "OFF",
      conteudo: "Por mais antigas que a história de Wycliffe, Huss e Jerônimo pareçam, não devemos pensar que isso foi algo que aconteceu apenas 'naquela época' com 'aquelas pessoas'. Há muitos países hoje em dia que continuam perseguindo os cristãos. Confira a lista com pelo menos dez deles: 1. Coreia do Norte; 2. Afeganistão; 3. Arábia Saudita; 4. Somália; 5. Irã; 6. Maldivas; 7. Uzbequistão; 8. Iêmen; 9. Iraque; 10. Paquistão.\n\nEm média anualmente, centenas de missionários de autossustento deixam seus países para servir em alguma parte do mundo. Essas pessoas estão dispostas a dar a vida para que a mensagem de salvação chegue a todas as nações, línguas e povos. São apaixonadas pela Bíblia e acreditam na transformação que o livro sagrado pode fazer na vida das pessoas porque ela revela os planos de Deus para salvar o ser humano.\n\nDepois de conhecer um pouco a história de como a Bíblia foi preservada ao longo dos anos para que tivéssemos condição de escolher o melhor caminho hoje, que decisão você deseja tomar em relação a ela?\n\n'Não tenha medo de investir na melhor Bíblia que você puder comprar – porque isso é o que você está fazendo: um investimento. Descubra por si mesmo por que ela responde a todas as necessidades humanas...'\n— BILLY GRAHAM\n\nALÉM DO ESTUDO: O que faz com que homens e mulheres amem tanto a Palavra de Deus a ponto de entregar a vida para defendê-la? Pesquise sobre quem foi Mary Jones. Acesse os capítulos 5 e 6 do livro Os Resgatados.",
      versiculoChave: { texto: "Não tenha medo de investir na melhor Bíblia que você puder comprar... é um investimento.", referencia: "Billy Graham" },
      perguntas: [
        { id: "d7q1", pergunta: "Quantos países são listados no texto como exemplos de perseguição religiosa atual?", opcoes: ["5", "10", "15", "20"], correta: 1, explicacao: "Uma lista com pelo menos 10 países." },
        { id: "d7q2", pergunta: "Segundo Billy Graham, investir na melhor Bíblia é, na verdade:", opcoes: ["Um desperdício", "Um investimento", "Uma obrigação legal", "Uma tradição"], correta: 1, explicacao: "É um investimento." },
        { id: "d7q3", pergunta: "Na seção 'Além do Estudo', qual adolescente é citada como exemplo de amor à Bíblia?", opcoes: ["Joana D'arc", "Mary Jones", "Ana Frank", "Helen Keller"], correta: 1, explicacao: "Mary Jones." },
        { id: "d7q4", pergunta: "Qual destes países está na lista de perseguição citada no texto?", opcoes: ["Coreia do Norte", "Canadá", "Brasil", "Portugal"], correta: 0, explicacao: "Coreia do Norte." }
      ]
    }
  ]
};
